apiVersion: v1
kind: PersistentVolume
namespace: expense
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0362018f02bf9b29  # should add the volume id whickh we createed
