kind: Service
apiVersion: v1
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:  #labels are used as selectors
    demo: lb
  ports:
    - protocol: TCP
      port: 80 #serviceport
      targetPort: 80 #target container port
      nodePort: 30007
---
kind: Pod
apiVersion: v1
metadata:
  name: backend-pod
  labels:
    demo: lb
spec:
  containers:
  - name: nginx
    image: nginx
